#ifndef ARTH
#define ARTH
#include <Arduino.h>

struct Image {
    int width;
    int height;
    int datalen;
    char charVal;
    unsigned char * data;
 };

extern const unsigned char LargeImgData_0 [] PROGMEM;
extern const unsigned char LargeImgData_1 [] PROGMEM;
extern const unsigned char LargeImgData_2 [] PROGMEM;
extern const unsigned char LargeImgData_3 [] PROGMEM;
extern const unsigned char LargeImgData_4 [] PROGMEM;
extern const unsigned char LargeImgData_5 [] PROGMEM;
extern const unsigned char LargeImgData_6 [] PROGMEM;
extern const unsigned char LargeImgData_7 [] PROGMEM;
extern const unsigned char LargeImgData_8 [] PROGMEM;
extern const unsigned char LargeImgData_9 [] PROGMEM;
extern const unsigned char LargeImgData_LA [] PROGMEM;
extern const unsigned char LargeImgData_LB [] PROGMEM;
extern const unsigned char LargeImgData_LC [] PROGMEM;
extern const unsigned char LargeImgData_LD [] PROGMEM;
extern const unsigned char LargeImgData_LE [] PROGMEM;
extern const unsigned char LargeImgData_LF [] PROGMEM;
extern const unsigned char LargeImgData_LG [] PROGMEM;
extern const unsigned char LargeImgData_LH [] PROGMEM;
extern const unsigned char LargeImgData_LI [] PROGMEM;
extern const unsigned char LargeImgData_LJ [] PROGMEM;
extern const unsigned char LargeImgData_LK [] PROGMEM;
extern const unsigned char LargeImgData_LL [] PROGMEM;
extern const unsigned char LargeImgData_LM [] PROGMEM;
extern const unsigned char LargeImgData_LN [] PROGMEM;
extern const unsigned char LargeImgData_LO [] PROGMEM;
extern const unsigned char LargeImgData_LP [] PROGMEM;
extern const unsigned char LargeImgData_LQ [] PROGMEM;
extern const unsigned char LargeImgData_LR [] PROGMEM;
extern const unsigned char LargeImgData_LS [] PROGMEM;
extern const unsigned char LargeImgData_LT [] PROGMEM;
extern const unsigned char LargeImgData_LU [] PROGMEM;
extern const unsigned char LargeImgData_LV [] PROGMEM;
extern const unsigned char LargeImgData_LW [] PROGMEM;
extern const unsigned char LargeImgData_LX [] PROGMEM;
extern const unsigned char LargeImgData_LY [] PROGMEM;
extern const unsigned char LargeImgData_LZ [] PROGMEM;
extern const unsigned char LargeImgData_SAND [] PROGMEM;
extern const unsigned char LargeImgData_SAST [] PROGMEM;
extern const unsigned char LargeImgData_SAT [] PROGMEM;
extern const unsigned char LargeImgData_SB1 [] PROGMEM;
extern const unsigned char LargeImgData_SB2 [] PROGMEM;
extern const unsigned char LargeImgData_SB3 [] PROGMEM;
extern const unsigned char LargeImgData_SB4 [] PROGMEM;
extern const unsigned char LargeImgData_SB5 [] PROGMEM;
extern const unsigned char LargeImgData_SB6 [] PROGMEM;
extern const unsigned char LargeImgData_SBS [] PROGMEM;
extern const unsigned char LargeImgData_SC [] PROGMEM;
extern const unsigned char LargeImgData_SC2 [] PROGMEM;
extern const unsigned char LargeImgData_SCOM [] PROGMEM;
extern const unsigned char LargeImgData_SD [] PROGMEM;
extern const unsigned char LargeImgData_SDQ [] PROGMEM;
extern const unsigned char LargeImgData_SE [] PROGMEM;
extern const unsigned char LargeImgData_SFS [] PROGMEM;
extern const unsigned char LargeImgData_SFS2 [] PROGMEM;
extern const unsigned char LargeImgData_SGT [] PROGMEM;
extern const unsigned char LargeImgData_SH [] PROGMEM;
extern const unsigned char LargeImgData_SHAT [] PROGMEM;
extern const unsigned char LargeImgData_SL [] PROGMEM;
extern const unsigned char LargeImgData_SLT [] PROGMEM;
extern const unsigned char LargeImgData_SMIN [] PROGMEM;
extern const unsigned char LargeImgData_SPC [] PROGMEM;
extern const unsigned char LargeImgData_SPL [] PROGMEM;
extern const unsigned char LargeImgData_SQ1 [] PROGMEM;
extern const unsigned char LargeImgData_SQ2 [] PROGMEM;
extern const unsigned char LargeImgData_SQM [] PROGMEM;
extern const unsigned char LargeImgData_ST [] PROGMEM;
extern const unsigned char LargeImgData_SUL [] PROGMEM;
extern const unsigned char LargeImgData_UA [] PROGMEM;
extern const unsigned char LargeImgData_UB [] PROGMEM;
extern const unsigned char LargeImgData_UC [] PROGMEM;
extern const unsigned char LargeImgData_UD [] PROGMEM;
extern const unsigned char LargeImgData_UE [] PROGMEM;
extern const unsigned char LargeImgData_UF [] PROGMEM;
extern const unsigned char LargeImgData_UG [] PROGMEM;
extern const unsigned char LargeImgData_UH [] PROGMEM;
extern const unsigned char LargeImgData_UI [] PROGMEM;
extern const unsigned char LargeImgData_UJ [] PROGMEM;
extern const unsigned char LargeImgData_UK [] PROGMEM;
extern const unsigned char LargeImgData_UL [] PROGMEM;
extern const unsigned char LargeImgData_UM [] PROGMEM;
extern const unsigned char LargeImgData_UN [] PROGMEM;
extern const unsigned char LargeImgData_UO [] PROGMEM;
extern const unsigned char LargeImgData_UP [] PROGMEM;
extern const unsigned char LargeImgData_UQ [] PROGMEM;
extern const unsigned char LargeImgData_UR [] PROGMEM;
extern const unsigned char LargeImgData_US [] PROGMEM;
extern const unsigned char LargeImgData_UT [] PROGMEM;
extern const unsigned char LargeImgData_UU [] PROGMEM;
extern const unsigned char LargeImgData_UV [] PROGMEM;
extern const unsigned char LargeImgData_UW [] PROGMEM;
extern const unsigned char LargeImgData_UX [] PROGMEM;
extern const unsigned char LargeImgData_UY [] PROGMEM;
extern const unsigned char LargeImgData_UZ [] PROGMEM;
extern const unsigned char LargeImgData_SPACE [] PROGMEM;

extern Image LargeImgData_0_Img;
extern Image LargeImgData_1_Img;
extern Image LargeImgData_2_Img;
extern Image LargeImgData_3_Img;
extern Image LargeImgData_4_Img;
extern Image LargeImgData_5_Img;
extern Image LargeImgData_6_Img;
extern Image LargeImgData_7_Img;
extern Image LargeImgData_8_Img;
extern Image LargeImgData_9_Img;
extern Image LargeImgData_LA_Img;
extern Image LargeImgData_LB_Img;
extern Image LargeImgData_LC_Img;
extern Image LargeImgData_LD_Img;
extern Image LargeImgData_LE_Img;
extern Image LargeImgData_LF_Img;
extern Image LargeImgData_LG_Img;
extern Image LargeImgData_LH_Img;
extern Image LargeImgData_LI_Img;
extern Image LargeImgData_LJ_Img;
extern Image LargeImgData_LK_Img;
extern Image LargeImgData_LL_Img;
extern Image LargeImgData_LM_Img;
extern Image LargeImgData_LN_Img;
extern Image LargeImgData_LO_Img;
extern Image LargeImgData_LP_Img;
extern Image LargeImgData_LQ_Img;
extern Image LargeImgData_LR_Img;
extern Image LargeImgData_LS_Img;
extern Image LargeImgData_LT_Img;
extern Image LargeImgData_LU_Img;
extern Image LargeImgData_LV_Img;
extern Image LargeImgData_LW_Img;
extern Image LargeImgData_LX_Img;
extern Image LargeImgData_LY_Img;
extern Image LargeImgData_LZ_Img;
extern Image LargeImgData_SAND_Img;
extern Image LargeImgData_SAST_Img;
extern Image LargeImgData_SAT_Img;
extern Image LargeImgData_SB1_Img;
extern Image LargeImgData_SB2_Img;
extern Image LargeImgData_SB3_Img;
extern Image LargeImgData_SB4_Img;
extern Image LargeImgData_SB5_Img;
extern Image LargeImgData_SB6_Img;
extern Image LargeImgData_SBS_Img;
extern Image LargeImgData_SC_Img;
extern Image LargeImgData_SC2_Img;
extern Image LargeImgData_SCOM_Img;
extern Image LargeImgData_SD_Img;
extern Image LargeImgData_SDQ_Img;
extern Image LargeImgData_SE_Img;
extern Image LargeImgData_SFS_Img;
extern Image LargeImgData_SFS2_Img;
extern Image LargeImgData_SGT_Img;
extern Image LargeImgData_SH_Img;
extern Image LargeImgData_SHAT_Img;
extern Image LargeImgData_SL_Img;
extern Image LargeImgData_SLT_Img;
extern Image LargeImgData_SMIN_Img;
extern Image LargeImgData_SPC_Img;
extern Image LargeImgData_SPL_Img;
extern Image LargeImgData_SQ1_Img;
extern Image LargeImgData_SQ2_Img;
extern Image LargeImgData_SQM_Img;
extern Image LargeImgData_ST_Img;
extern Image LargeImgData_SUL_Img;
extern Image LargeImgData_UA_Img;
extern Image LargeImgData_UB_Img;
extern Image LargeImgData_UC_Img;
extern Image LargeImgData_UD_Img;
extern Image LargeImgData_UE_Img;
extern Image LargeImgData_UF_Img;
extern Image LargeImgData_UG_Img;
extern Image LargeImgData_UH_Img;
extern Image LargeImgData_UI_Img;
extern Image LargeImgData_UJ_Img;
extern Image LargeImgData_UK_Img;
extern Image LargeImgData_UL_Img;
extern Image LargeImgData_UM_Img;
extern Image LargeImgData_UN_Img;
extern Image LargeImgData_UO_Img;
extern Image LargeImgData_UP_Img;
extern Image LargeImgData_UQ_Img;
extern Image LargeImgData_UR_Img;
extern Image LargeImgData_US_Img;
extern Image LargeImgData_UT_Img;
extern Image LargeImgData_UU_Img;
extern Image LargeImgData_UV_Img;
extern Image LargeImgData_UW_Img;
extern Image LargeImgData_UX_Img;
extern Image LargeImgData_UY_Img;
extern Image LargeImgData_UZ_Img;
extern Image LargeImgData_SPACE_Img;


extern const unsigned char MediumImgData_0 [] PROGMEM;
extern const unsigned char MediumImgData_1 [] PROGMEM;
extern const unsigned char MediumImgData_2 [] PROGMEM;
extern const unsigned char MediumImgData_3 [] PROGMEM;
extern const unsigned char MediumImgData_4 [] PROGMEM;
extern const unsigned char MediumImgData_5 [] PROGMEM;
extern const unsigned char MediumImgData_6 [] PROGMEM;
extern const unsigned char MediumImgData_7 [] PROGMEM;
extern const unsigned char MediumImgData_8 [] PROGMEM;
extern const unsigned char MediumImgData_9 [] PROGMEM;
extern const unsigned char MediumImgData_LA [] PROGMEM;
extern const unsigned char MediumImgData_LB [] PROGMEM;
extern const unsigned char MediumImgData_LC [] PROGMEM;
extern const unsigned char MediumImgData_LD [] PROGMEM;
extern const unsigned char MediumImgData_LE [] PROGMEM;
extern const unsigned char MediumImgData_LF [] PROGMEM;
extern const unsigned char MediumImgData_LG [] PROGMEM;
extern const unsigned char MediumImgData_LH [] PROGMEM;
extern const unsigned char MediumImgData_LI [] PROGMEM;
extern const unsigned char MediumImgData_LJ [] PROGMEM;
extern const unsigned char MediumImgData_LK [] PROGMEM;
extern const unsigned char MediumImgData_LL [] PROGMEM;
extern const unsigned char MediumImgData_LM [] PROGMEM;
extern const unsigned char MediumImgData_LN [] PROGMEM;
extern const unsigned char MediumImgData_LO [] PROGMEM;
extern const unsigned char MediumImgData_LP [] PROGMEM;
extern const unsigned char MediumImgData_LQ [] PROGMEM;
extern const unsigned char MediumImgData_LR [] PROGMEM;
extern const unsigned char MediumImgData_LS [] PROGMEM;
extern const unsigned char MediumImgData_LT [] PROGMEM;
extern const unsigned char MediumImgData_LU [] PROGMEM;
extern const unsigned char MediumImgData_LV [] PROGMEM;
extern const unsigned char MediumImgData_LW [] PROGMEM;
extern const unsigned char MediumImgData_LX [] PROGMEM;
extern const unsigned char MediumImgData_LY [] PROGMEM;
extern const unsigned char MediumImgData_LZ [] PROGMEM;
extern const unsigned char MediumImgData_SAND [] PROGMEM;
extern const unsigned char MediumImgData_SAST [] PROGMEM;
extern const unsigned char MediumImgData_SAT [] PROGMEM;
extern const unsigned char MediumImgData_SB1 [] PROGMEM;
extern const unsigned char MediumImgData_SB2 [] PROGMEM;
extern const unsigned char MediumImgData_SB3 [] PROGMEM;
extern const unsigned char MediumImgData_SB4 [] PROGMEM;
extern const unsigned char MediumImgData_SB5 [] PROGMEM;
extern const unsigned char MediumImgData_SB6 [] PROGMEM;
extern const unsigned char MediumImgData_SBS [] PROGMEM;
extern const unsigned char MediumImgData_SC [] PROGMEM;
extern const unsigned char MediumImgData_SC2 [] PROGMEM;
extern const unsigned char MediumImgData_SCOM [] PROGMEM;
extern const unsigned char MediumImgData_SD [] PROGMEM;
extern const unsigned char MediumImgData_SDQ [] PROGMEM;
extern const unsigned char MediumImgData_SE [] PROGMEM;
extern const unsigned char MediumImgData_SFS [] PROGMEM;
extern const unsigned char MediumImgData_SFS2 [] PROGMEM;
extern const unsigned char MediumImgData_SGT [] PROGMEM;
extern const unsigned char MediumImgData_SH [] PROGMEM;
extern const unsigned char MediumImgData_SHAT [] PROGMEM;
extern const unsigned char MediumImgData_SL [] PROGMEM;
extern const unsigned char MediumImgData_SLT [] PROGMEM;
extern const unsigned char MediumImgData_SMIN [] PROGMEM;
extern const unsigned char MediumImgData_SPC [] PROGMEM;
extern const unsigned char MediumImgData_SPL [] PROGMEM;
extern const unsigned char MediumImgData_SQ1 [] PROGMEM;
extern const unsigned char MediumImgData_SQ2 [] PROGMEM;
extern const unsigned char MediumImgData_SQM [] PROGMEM;
extern const unsigned char MediumImgData_ST [] PROGMEM;
extern const unsigned char MediumImgData_SUL [] PROGMEM;
extern const unsigned char MediumImgData_UA [] PROGMEM;
extern const unsigned char MediumImgData_UB [] PROGMEM;
extern const unsigned char MediumImgData_UC [] PROGMEM;
extern const unsigned char MediumImgData_UD [] PROGMEM;
extern const unsigned char MediumImgData_UE [] PROGMEM;
extern const unsigned char MediumImgData_UF [] PROGMEM;
extern const unsigned char MediumImgData_UG [] PROGMEM;
extern const unsigned char MediumImgData_UH [] PROGMEM;
extern const unsigned char MediumImgData_UI [] PROGMEM;
extern const unsigned char MediumImgData_UJ [] PROGMEM;
extern const unsigned char MediumImgData_UK [] PROGMEM;
extern const unsigned char MediumImgData_UL [] PROGMEM;
extern const unsigned char MediumImgData_UM [] PROGMEM;
extern const unsigned char MediumImgData_UN [] PROGMEM;
extern const unsigned char MediumImgData_UO [] PROGMEM;
extern const unsigned char MediumImgData_UP [] PROGMEM;
extern const unsigned char MediumImgData_UQ [] PROGMEM;
extern const unsigned char MediumImgData_UR [] PROGMEM;
extern const unsigned char MediumImgData_US [] PROGMEM;
extern const unsigned char MediumImgData_UT [] PROGMEM;
extern const unsigned char MediumImgData_UU [] PROGMEM;
extern const unsigned char MediumImgData_UV [] PROGMEM;
extern const unsigned char MediumImgData_UW [] PROGMEM;
extern const unsigned char MediumImgData_UX [] PROGMEM;
extern const unsigned char MediumImgData_UY [] PROGMEM;
extern const unsigned char MediumImgData_UZ [] PROGMEM;
extern const unsigned char MediumImgData_SPACE [] PROGMEM;

extern Image MediumImgData_0_Img;
extern Image MediumImgData_1_Img;
extern Image MediumImgData_2_Img;
extern Image MediumImgData_3_Img;
extern Image MediumImgData_4_Img;
extern Image MediumImgData_5_Img;
extern Image MediumImgData_6_Img;
extern Image MediumImgData_7_Img;
extern Image MediumImgData_8_Img;
extern Image MediumImgData_9_Img;
extern Image MediumImgData_LA_Img;
extern Image MediumImgData_LB_Img;
extern Image MediumImgData_LC_Img;
extern Image MediumImgData_LD_Img;
extern Image MediumImgData_LE_Img;
extern Image MediumImgData_LF_Img;
extern Image MediumImgData_LG_Img;
extern Image MediumImgData_LH_Img;
extern Image MediumImgData_LI_Img;
extern Image MediumImgData_LJ_Img;
extern Image MediumImgData_LK_Img;
extern Image MediumImgData_LL_Img;
extern Image MediumImgData_LM_Img;
extern Image MediumImgData_LN_Img;
extern Image MediumImgData_LO_Img;
extern Image MediumImgData_LP_Img;
extern Image MediumImgData_LQ_Img;
extern Image MediumImgData_LR_Img;
extern Image MediumImgData_LS_Img;
extern Image MediumImgData_LT_Img;
extern Image MediumImgData_LU_Img;
extern Image MediumImgData_LV_Img;
extern Image MediumImgData_LW_Img;
extern Image MediumImgData_LX_Img;
extern Image MediumImgData_LY_Img;
extern Image MediumImgData_LZ_Img;
extern Image MediumImgData_SAND_Img;
extern Image MediumImgData_SAST_Img;
extern Image MediumImgData_SAT_Img;
extern Image MediumImgData_SB1_Img;
extern Image MediumImgData_SB2_Img;
extern Image MediumImgData_SB3_Img;
extern Image MediumImgData_SB4_Img;
extern Image MediumImgData_SB5_Img;
extern Image MediumImgData_SB6_Img;
extern Image MediumImgData_SBS_Img;
extern Image MediumImgData_SC_Img;
extern Image MediumImgData_SC2_Img;
extern Image MediumImgData_SCOM_Img;
extern Image MediumImgData_SD_Img;
extern Image MediumImgData_SDQ_Img;
extern Image MediumImgData_SE_Img;
extern Image MediumImgData_SFS_Img;
extern Image MediumImgData_SFS2_Img;
extern Image MediumImgData_SGT_Img;
extern Image MediumImgData_SH_Img;
extern Image MediumImgData_SHAT_Img;
extern Image MediumImgData_SL_Img;
extern Image MediumImgData_SLT_Img;
extern Image MediumImgData_SMIN_Img;
extern Image MediumImgData_SPC_Img;
extern Image MediumImgData_SPL_Img;
extern Image MediumImgData_SQ1_Img;
extern Image MediumImgData_SQ2_Img;
extern Image MediumImgData_SQM_Img;
extern Image MediumImgData_ST_Img;
extern Image MediumImgData_SUL_Img;
extern Image MediumImgData_UA_Img;
extern Image MediumImgData_UB_Img;
extern Image MediumImgData_UC_Img;
extern Image MediumImgData_UD_Img;
extern Image MediumImgData_UE_Img;
extern Image MediumImgData_UF_Img;
extern Image MediumImgData_UG_Img;
extern Image MediumImgData_UH_Img;
extern Image MediumImgData_UI_Img;
extern Image MediumImgData_UJ_Img;
extern Image MediumImgData_UK_Img;
extern Image MediumImgData_UL_Img;
extern Image MediumImgData_UM_Img;
extern Image MediumImgData_UN_Img;
extern Image MediumImgData_UO_Img;
extern Image MediumImgData_UP_Img;
extern Image MediumImgData_UQ_Img;
extern Image MediumImgData_UR_Img;
extern Image MediumImgData_US_Img;
extern Image MediumImgData_UT_Img;
extern Image MediumImgData_UU_Img;
extern Image MediumImgData_UV_Img;
extern Image MediumImgData_UW_Img;
extern Image MediumImgData_UX_Img;
extern Image MediumImgData_UY_Img;
extern Image MediumImgData_UZ_Img;
extern Image MediumImgData_SPACE_Img;

extern const unsigned char SmallImgData_0 [] PROGMEM;
extern const unsigned char SmallImgData_1 [] PROGMEM;
extern const unsigned char SmallImgData_2 [] PROGMEM;
extern const unsigned char SmallImgData_3 [] PROGMEM;
extern const unsigned char SmallImgData_4 [] PROGMEM;
extern const unsigned char SmallImgData_5 [] PROGMEM;
extern const unsigned char SmallImgData_6 [] PROGMEM;
extern const unsigned char SmallImgData_7 [] PROGMEM;
extern const unsigned char SmallImgData_8 [] PROGMEM;
extern const unsigned char SmallImgData_9 [] PROGMEM;
extern const unsigned char SmallImgData_LA [] PROGMEM;
extern const unsigned char SmallImgData_LB [] PROGMEM;
extern const unsigned char SmallImgData_LC [] PROGMEM;
extern const unsigned char SmallImgData_LD [] PROGMEM;
extern const unsigned char SmallImgData_LE [] PROGMEM;
extern const unsigned char SmallImgData_LF [] PROGMEM;
extern const unsigned char SmallImgData_LG [] PROGMEM;
extern const unsigned char SmallImgData_LH [] PROGMEM;
extern const unsigned char SmallImgData_LI [] PROGMEM;
extern const unsigned char SmallImgData_LJ [] PROGMEM;
extern const unsigned char SmallImgData_LK [] PROGMEM;
extern const unsigned char SmallImgData_LL [] PROGMEM;
extern const unsigned char SmallImgData_LM [] PROGMEM;
extern const unsigned char SmallImgData_LN [] PROGMEM;
extern const unsigned char SmallImgData_LO [] PROGMEM;
extern const unsigned char SmallImgData_LP [] PROGMEM;
extern const unsigned char SmallImgData_LQ [] PROGMEM;
extern const unsigned char SmallImgData_LR [] PROGMEM;
extern const unsigned char SmallImgData_LS [] PROGMEM;
extern const unsigned char SmallImgData_LT [] PROGMEM;
extern const unsigned char SmallImgData_LU [] PROGMEM;
extern const unsigned char SmallImgData_LV [] PROGMEM;
extern const unsigned char SmallImgData_LW [] PROGMEM;
extern const unsigned char SmallImgData_LX [] PROGMEM;
extern const unsigned char SmallImgData_LY [] PROGMEM;
extern const unsigned char SmallImgData_LZ [] PROGMEM;
extern const unsigned char SmallImgData_SAND [] PROGMEM;
extern const unsigned char SmallImgData_SAST [] PROGMEM;
extern const unsigned char SmallImgData_SAT [] PROGMEM;
extern const unsigned char SmallImgData_SB1 [] PROGMEM;
extern const unsigned char SmallImgData_SB2 [] PROGMEM;
extern const unsigned char SmallImgData_SB3 [] PROGMEM;
extern const unsigned char SmallImgData_SB4 [] PROGMEM;
extern const unsigned char SmallImgData_SB5 [] PROGMEM;
extern const unsigned char SmallImgData_SB6 [] PROGMEM;
extern const unsigned char SmallImgData_SBS [] PROGMEM;
extern const unsigned char SmallImgData_SC [] PROGMEM;
extern const unsigned char SmallImgData_SC2 [] PROGMEM;
extern const unsigned char SmallImgData_SCOM [] PROGMEM;
extern const unsigned char SmallImgData_SD [] PROGMEM;
extern const unsigned char SmallImgData_SDQ [] PROGMEM;
extern const unsigned char SmallImgData_SE [] PROGMEM;
extern const unsigned char SmallImgData_SFS [] PROGMEM;
extern const unsigned char SmallImgData_SFS2 [] PROGMEM;
extern const unsigned char SmallImgData_SGT [] PROGMEM;
extern const unsigned char SmallImgData_SH [] PROGMEM;
extern const unsigned char SmallImgData_SHAT [] PROGMEM;
extern const unsigned char SmallImgData_SL [] PROGMEM;
extern const unsigned char SmallImgData_SLT [] PROGMEM;
extern const unsigned char SmallImgData_SMIN [] PROGMEM;
extern const unsigned char SmallImgData_SPC [] PROGMEM;
extern const unsigned char SmallImgData_SPL [] PROGMEM;
extern const unsigned char SmallImgData_SQ1 [] PROGMEM;
extern const unsigned char SmallImgData_SQ2 [] PROGMEM;
extern const unsigned char SmallImgData_SQM [] PROGMEM;
extern const unsigned char SmallImgData_ST [] PROGMEM;
extern const unsigned char SmallImgData_SUL [] PROGMEM;
extern const unsigned char SmallImgData_UA [] PROGMEM;
extern const unsigned char SmallImgData_UB [] PROGMEM;
extern const unsigned char SmallImgData_UC [] PROGMEM;
extern const unsigned char SmallImgData_UD [] PROGMEM;
extern const unsigned char SmallImgData_UE [] PROGMEM;
extern const unsigned char SmallImgData_UF [] PROGMEM;
extern const unsigned char SmallImgData_UG [] PROGMEM;
extern const unsigned char SmallImgData_UH [] PROGMEM;
extern const unsigned char SmallImgData_UI [] PROGMEM;
extern const unsigned char SmallImgData_UJ [] PROGMEM;
extern const unsigned char SmallImgData_UK [] PROGMEM;
extern const unsigned char SmallImgData_UL [] PROGMEM;
extern const unsigned char SmallImgData_UM [] PROGMEM;
extern const unsigned char SmallImgData_UN [] PROGMEM;
extern const unsigned char SmallImgData_UO [] PROGMEM;
extern const unsigned char SmallImgData_UP [] PROGMEM;
extern const unsigned char SmallImgData_UQ [] PROGMEM;
extern const unsigned char SmallImgData_UR [] PROGMEM;
extern const unsigned char SmallImgData_US [] PROGMEM;
extern const unsigned char SmallImgData_UT [] PROGMEM;
extern const unsigned char SmallImgData_UU [] PROGMEM;
extern const unsigned char SmallImgData_UV [] PROGMEM;
extern const unsigned char SmallImgData_UW [] PROGMEM;
extern const unsigned char SmallImgData_UX [] PROGMEM;
extern const unsigned char SmallImgData_UY [] PROGMEM;
extern const unsigned char SmallImgData_UZ [] PROGMEM;
extern const unsigned char SmallImgData_SPACE [] PROGMEM;

extern Image SmallImgData_0_Img;
extern Image SmallImgData_1_Img;
extern Image SmallImgData_2_Img;
extern Image SmallImgData_3_Img;
extern Image SmallImgData_4_Img;
extern Image SmallImgData_5_Img;
extern Image SmallImgData_6_Img;
extern Image SmallImgData_7_Img;
extern Image SmallImgData_8_Img;
extern Image SmallImgData_9_Img;
extern Image SmallImgData_LA_Img;
extern Image SmallImgData_LB_Img;
extern Image SmallImgData_LC_Img;
extern Image SmallImgData_LD_Img;
extern Image SmallImgData_LE_Img;
extern Image SmallImgData_LF_Img;
extern Image SmallImgData_LG_Img;
extern Image SmallImgData_LH_Img;
extern Image SmallImgData_LI_Img;
extern Image SmallImgData_LJ_Img;
extern Image SmallImgData_LK_Img;
extern Image SmallImgData_LL_Img;
extern Image SmallImgData_LM_Img;
extern Image SmallImgData_LN_Img;
extern Image SmallImgData_LO_Img;
extern Image SmallImgData_LP_Img;
extern Image SmallImgData_LQ_Img;
extern Image SmallImgData_LR_Img;
extern Image SmallImgData_LS_Img;
extern Image SmallImgData_LT_Img;
extern Image SmallImgData_LU_Img;
extern Image SmallImgData_LV_Img;
extern Image SmallImgData_LW_Img;
extern Image SmallImgData_LX_Img;
extern Image SmallImgData_LY_Img;
extern Image SmallImgData_LZ_Img;
extern Image SmallImgData_SAND_Img;
extern Image SmallImgData_SAST_Img;
extern Image SmallImgData_SAT_Img;
extern Image SmallImgData_SB1_Img;
extern Image SmallImgData_SB2_Img;
extern Image SmallImgData_SB3_Img;
extern Image SmallImgData_SB4_Img;
extern Image SmallImgData_SB5_Img;
extern Image SmallImgData_SB6_Img;
extern Image SmallImgData_SBS_Img;
extern Image SmallImgData_SC_Img;
extern Image SmallImgData_SC2_Img;
extern Image SmallImgData_SCOM_Img;
extern Image SmallImgData_SD_Img;
extern Image SmallImgData_SDQ_Img;
extern Image SmallImgData_SE_Img;
extern Image SmallImgData_SFS_Img;
extern Image SmallImgData_SFS2_Img;
extern Image SmallImgData_SGT_Img;
extern Image SmallImgData_SH_Img;
extern Image SmallImgData_SHAT_Img;
extern Image SmallImgData_SL_Img;
extern Image SmallImgData_SLT_Img;
extern Image SmallImgData_SMIN_Img;
extern Image SmallImgData_SPC_Img;
extern Image SmallImgData_SPL_Img;
extern Image SmallImgData_SQ1_Img;
extern Image SmallImgData_SQ2_Img;
extern Image SmallImgData_SQM_Img;
extern Image SmallImgData_ST_Img;
extern Image SmallImgData_SUL_Img;
extern Image SmallImgData_UA_Img;
extern Image SmallImgData_UB_Img;
extern Image SmallImgData_UC_Img;
extern Image SmallImgData_UD_Img;
extern Image SmallImgData_UE_Img;
extern Image SmallImgData_UF_Img;
extern Image SmallImgData_UG_Img;
extern Image SmallImgData_UH_Img;
extern Image SmallImgData_UI_Img;
extern Image SmallImgData_UJ_Img;
extern Image SmallImgData_UK_Img;
extern Image SmallImgData_UL_Img;
extern Image SmallImgData_UM_Img;
extern Image SmallImgData_UN_Img;
extern Image SmallImgData_UO_Img;
extern Image SmallImgData_UP_Img;
extern Image SmallImgData_UQ_Img;
extern Image SmallImgData_UR_Img;
extern Image SmallImgData_US_Img;
extern Image SmallImgData_UT_Img;
extern Image SmallImgData_UU_Img;
extern Image SmallImgData_UV_Img;
extern Image SmallImgData_UW_Img;
extern Image SmallImgData_UX_Img;
extern Image SmallImgData_UY_Img;
extern Image SmallImgData_UZ_Img;
extern Image SmallImgData_SPACE_Img;


extern const unsigned char ImgData_SDeg[] PROGMEM;
extern const unsigned char ImgData_MDeg[] PROGMEM;
extern const unsigned char ImgData_LDeg[] PROGMEM;
extern Image ImgData_SDeg_Img;
extern Image ImgData_MDeg_Img;
extern Image ImgData_LDeg_Img;

extern const unsigned char Speedo100[] PROGMEM;
extern const unsigned char Speedo50[] PROGMEM;
extern const unsigned char Speedo75[] PROGMEM;
extern const unsigned char SpeedoCentreGlowOption[] PROGMEM;
extern const unsigned char SpeedoLargeTicks[] PROGMEM;
extern const unsigned char SpeedoNeedle[] PROGMEM;
extern const unsigned char SpeedoSideBar[] PROGMEM;
extern const unsigned char SpeedoSmallTicks[] PROGMEM;

extern Image Speedo100_Img;
extern Image Speedo50_Img;
extern Image Speedo75_Img;
extern Image SpeedoCentreGlowOption_Img;
extern Image SpeedoLargeTicks_Img;
extern Image SpeedoNeedle_Img;
extern Image SpeedoSideBar_Img;
extern Image SpeedoSmallTicks_Img;

extern int bitmap_LargeallArrayMax;
extern Image * bitmap_LargeallArray[];
extern int bitmap_MedallArrayMax;
extern Image * bitmap_MedallArray[];
extern int bitmap_MedallArrayMax2;
extern Image * bitmap_MedallArray2[];
extern Image ** bitmapArrays[];
extern int * maxDigitArray[];

#endif
